### PR TITLE
Add NDK r26

### PR DESCRIPTION
**Pull request by zebede22**
Add latest  NDK LTS:
https://github.com/android/ndk/wiki

Package for darwin systems are not provided as zip anymore but as .dmg files.
I don't know how  to handle them, so skipping for now

### CODE REVIEW

**Comment by SirLynix** [comment]
@waruqi how should xmake deal with .dmg files?

**Comment by zebede22** [comment]
> @waruqi how should xmake deal with .dmg files?

There is this one using .dmg but not sure how it works:
https://github.com/xmake-io/xmake-repo/blob/1cc96876e1f9895553498214897ba3d5a368e83e/packages/i/ifort/xmake.lua#L18

**Comment by SirLynix** [comment]
nevermind, the .zip file exists for macOS too

**Comment by waruqi** [comment]
> > @waruqi how should xmake deal with .dmg files?
> 
> There is this one using .dmg but not sure how it works:
> 
> https://github.com/xmake-io/xmake-repo/blob/1cc96876e1f9895553498214897ba3d5a368e83e/packages/i/ifort/xmake.lua#L18

here

https://github.com/xmake-io/xmake-repo/blob/1cc96876e1f9895553498214897ba3d5a368e83e/packages/i/ifort/xmake.lua#L53

But the code here never seems to get executed to, and I'm not sure it would work.

**Comment by waruqi** [comment]
> > @waruqi how should xmake deal with .dmg files?
> 
> There is this one using .dmg but not sure how it works:
> 
> https://github.com/xmake-io/xmake-repo/blob/1cc96876e1f9895553498214897ba3d5a368e83e/packages/i/ifort/xmake.lua#L18

here

https://github.com/xmake-io/xmake-repo/blob/1cc96876e1f9895553498214897ba3d5a368e83e/packages/i/ifort/xmake.lua#L53

But the code here never seems to get executed to, and I'm not sure it would work.

**Pull request merged**
