### PR TITLE
TiltedCore 0.2.3

### PR DESCRIPTION
**Pull request by yamashi**

### CODE REVIEW

**Comment by waruqi** [comment]
> C:\Users\runneradmin\AppData\Local\.xmake\packages\t\tiltedcore\v0.2.3\6957e066ad9d40ba905dc031de564be1\include\TiltedCore/Outcome.hpp(68): error C2429: attribute 'nodiscard' requires compiler flag '/std:c++17'

this lib only support vs2019?

**Comment by yamashi** [comment]
It requires a C++17 compiler yes

**Comment by waruqi** [comment]
ok

**Comment by waruqi** [comment]
can you add some tips? lile this 

https://github.com/xmake-io/xmake-repo/pull/542/commits/aa59336eca917632b6f074f9dca23ab21fe78695

**Pull request merged**
