### PR TITLE
[commonlibsse-ng] Edit `spdlog` dependency

### PR DESCRIPTION
**Pull request by Qudix**
Set `spdlog`'s `header_only` option to false

### CODE REVIEW

**Comment by waruqi** [comment]
why?

**Comment by Qudix** [comment]
Header only brings in `Windows.h` and we had some issues caused by this requiring us to create workarounds. With this we can remove them.

**Comment by waruqi** [comment]
you can use `add_requireconfs("commonlibsse-ng.spdlog", { configs = { header_only = false } })` to override it in user side.

and if Windows.h will bring some issues, we can add patches to fix it.

**Comment by waruqi** [comment]
Switching the default dependency configuration doesn't solve the problem at all, it just hides it. And there is a risk of breaking existing users' projects.

**Comment by Qudix** [comment]
I can count the users of this package on one hand as they all use my project and there should be no risk of breakage. Also commonlibsse-ng already made similar changes for the vcpkg port.

**Comment by waruqi** [comment]
> I can count the users of this package on one hand as they all use my project and there should be no risk of breakage. Also commonlibsse-ng already made similar changes for the vcpkg port.

? I'm not sure how you counted, commonlibsse-ng is your project? so you can count it?

**Comment by Qudix** [comment]
No, people using commonlibsse-ng directly use vcpkg, I made the xmake port for use in my template project
https://github.com/Qudix/template-commonlibsse-ng

**Comment by waruqi** [comment]
> No, people using commonlibsse-ng directly use vcpkg, I made the xmake port for use in my template project https://github.com/Qudix/template-commonlibsse-ng

so you can add `add_requireconfs("commonlibsse-ng.spdlog", { configs = { header_only = false } })` in your xmake.lua

Also, it is possible that other users are using this package and I am not sure if it will have an effect.

**Comment by Qudix** [comment]
I don't want to do that, this should be a simple change with no unwanted effects. I know exactly who else is using this and they all go through me.

**Comment by waruqi** [comment]
ok, but please fix some errors on ci.

**Pull request merged**
