### PR TITLE
zstd: use cmake

### PR DESCRIPTION
**Pull request by star-hengxing**
- zstd
  - Add config
    - cmake (default: true)
    - tools
    - contrib
- microsoft-seal
  - Remove zstd patch
- libdwarf
  - Support more platform
  - Fix `find_package` zstd
  - Add config
    - tools

### CODE REVIEW

**Comment by da-liii** [comment]
it seems https://github.com/XmacsLabs/mogan/pull/2201 failed to build because of this pull request

**Comment by da-liii** [comment]
How I fixed this issue:
+ https://github.com/XmacsLabs/mogan/blob/branch-1.2/xmake/packages/z/zlib/xmake.lua
+ https://github.com/XmacsLabs/mogan/blob/da/73_37/retry/xmake/packages/l/libdwarf/xmake.lua

Thanks for contributing to xmake-repo. And I suggest that we should default to xmake build when there is already a xmake build definition available in the repo.

**Comment by star-hengxing** [comment]
> And I suggest that we should default to xmake build when there is already a xmake build definition available in the repo.

Advantages of using the library's own build system (cmake):

- No need to synchronously update `xmake.lua` to avoid missing builds of `.c/.cpp` files.
- `XXXTargets.cmake`, `XXXConfig.cmake` help downstream cmake to use find_package.

And this pr is to fix the downstream find_package error https://github.com/xmake-io/xmake-repo/pull/5844

**Comment by waruqi** [comment]
切 cmake 本身没啥问题，但按理即使切到了 cmake ，对用户端使用 应该也不会 break 才对。。是有啥差异么，可以贴 errors logs或者直接提 pr 改进下 目前 cmake 的实现

**Comment by star-hengxing** [comment]
> 切 cmake 本身没啥问题，但按理即使切到了 cmake ，对用户端使用 应该也不会 break 才对。。是有啥差异么，可以贴 errors logs或者直接提 pr 改进下 目前 cmake 的实现

唯一会 break 的就是下游 cmake 包的构建。但原来用 xmake 构建没有 cmake config file 的安装，应该本来就有问题。

刚刚发现了一处，应该和 xmake 构建完全一样了。
https://github.com/xmake-io/xmake-repo/commit/bd2a28f2bbb01cd730cb2dfdd3ae39860394318e

**Pull request merged**
