### PR TITLE
Add libflac

### PR DESCRIPTION
**Pull request by SirLynix**
From #203

### CODE REVIEW

**Comment by waruqi** [comment]
on macOS


> /Users/runner/.xmake/packages/l/libogg/1.3.4/d639b7d6e3244216b403b39df5101abf/include/ogg/os_types.h:75:12: error: unknown type name 'uint16_t'
   typedef uint16_t ogg_uint16_t;
           ^
/Users/runner/.xmake/packages/l/libogg/1.3.4/d639b7d6e3244216b403b39df5101abf/include/ogg/os_types.h:77:12: error: unknown type name 'uint32_t'
   typedef uint32_t ogg_uint32_t;
           ^
/Users/runner/.xmake/packages/l/libogg/1.3.4/d639b7d6e3244216b403b39df5101abf/include/ogg/os_types.h:79:12: error: unknown type name 'uint64_t'
   typedef uint64_t ogg_uint64_t;
           
try add stdint.h on tests?

```
        assert(package:has_cfuncs("FLAC__format_sample_rate_is_valid", {includes = {"stdint.h", "FLAC/format.h"}}))
```

**Comment by SirLynix** [comment]
> try add stdint.h on tests?

It's not failing on tests but on libflac compilation.

It seems to come from libogg, compare [1.3.4 code](https://github.com/xiph/ogg/blob/bada45718453ac27b56773ae663f7e65112f6a6e/include/ogg/os_types.h#L75) with [master code](https://github.com/xiph/ogg/blob/master/include/ogg/os_types.h#L75).

Maybe libogg should be patched for macOS?

**Comment by waruqi** [comment]
> > try add stdint.h on tests?
> 
> It's not failing on tests but on libflac compilation.
> 
> It seems to come from libogg, compare [1.3.4 code](https://github.com/xiph/ogg/blob/bada45718453ac27b56773ae663f7e65112f6a6e/include/ogg/os_types.h#L75) with [master code](https://github.com/xiph/ogg/blob/master/include/ogg/os_types.h#L75).
> 
> Maybe libogg should be patched for macOS?

maybe, or you can also use special master commit in add_versions

**Comment by SirLynix** [comment]
From what I see in the [commits since 1.3.4](https://github.com/xiph/ogg/compare/v1.3.4...master) there's not much code change since master. But isn't it better to have a version that can be downloaded from a .tar.gz instead of always relying on git?

I'm willing to either patch the code for macOS or switch to master, whatever you think is the best.

However there's still that 
```
  Could NOT find OGG (missing: OGG_INCLUDE_DIR OGG_LIBRARY) (found version
  "1.3.4")
```
errors for other targets. I'm lost about it.

**Comment by waruqi** [comment]
>   Could NOT find OGG (missing: OGG_INCLUDE_DIR OGG_LIBRARY) (found version
>   "1.3.4")

I will look at it when I have time, and maybe need to patch FindOgg.cmake.

**Comment by waruqi** [comment]
I have fixed it and merge this patch. see https://github.com/xmake-io/xmake-repo/pull/212

> /usr/local/Cellar/mingw-w64/8.0.0/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: CMakeFiles/FLAC.dir/objects.a(metadata_iterators.c.obj):metadata_iterators.c:(.text+0x1966): undefined reference to `__memset_chk'

You can refer https://github.com/msys2/MINGW-packages/issues/5803

**Pull request closed without merging**
