### PR TITLE
pango: Fix unexpected -Werror=... errors

### PR DESCRIPTION
**Pull request by SuperSodaSea**
See also: #2780, <https://gitlab.gnome.org/GNOME/pango/-/issues/740>

### CODE REVIEW

**Comment by waruqi** [comment]
and macos

**Comment by SuperSodaSea** [comment]
openssl 1.1.1-t seems to be broken for some reason...

**Comment by waruqi** [comment]
maybe this patch broken it. we will fix it. https://github.com/xmake-io/xmake/pull/4358

**Comment by SuperSodaSea** [comment]
Seems that OpenBSD (a8b7d88613e9167653478fff6b330770c32a4a0d) is broken?

**Pull request merged**
