### PR TITLE
add package dxsdk

### PR DESCRIPTION
**Pull request by ChrisCatCP**

### CODE REVIEW

**Comment by SirLynix** [comment]
This packages misses protected vs_runtime and shared configs

**Comment by waruqi** [comment]
> This packages misses protected vs_runtime and shared configs

has shared configs, just no vs_runtime

**Comment by waruqi** [comment]
@ChrisCatCP Can you improve it again? add vs runtime as readonly and use `is_plat` and `is_arch` instead of is_host

**Comment by SirLynix** [comment]
vs_runtime should be MD in release and MDd in debug, is there a way to do that?

**Comment by ChrisCatCP** [comment]
i think vs_runtime is invalid here

**Pull request merged**
