### PR TITLE
aqt: Add version 3.1.17

### PR DESCRIPTION
**Pull request by SirLynix**
and drop support for signed versions as they're no longer produced

### CODE REVIEW

**Comment by SirLynix** [comment]
macOS fails with
> cannot runv(aqt -h), Not access because it is busy
what could cause this error?

**Comment by waruqi** [comment]
> { 
  "aqt 3.1.17",
  "aqt 3.1.6",
  "aqt 3.0.2",
  "aqt 2.0.6", 
}

four aqt test processes?

**Comment by SirLynix** [comment]
that's because I removed the signed prefix on Windows, it shouldn't be a big deal except on macOS where those versions don't exist.

however I have a busy error on the existing version

**Comment by SirLynix** [comment]
After digging a bit it's a EACCES error, caused by a missing executable permission. how can I chmod +x using xmake?

**Comment by waruqi** [comment]
os.exec + chmod https://github.com/xmake-io/xmake-repo/blob/c05eb260a8ff354b6226cdbbbb74c7e6ab313718/packages/b/bazel/xmake.lua#L36

**Pull request merged**
