### PR TITLE
JoltPhysics: Add missing public defines

### PR DESCRIPTION
**Pull request by SirLynix**
As seen here:
https://github.com/jrouwe/JoltPhysics/blob/f16f2a098ae2c4ef32f537a9b260bc2e11a00987/Jolt/Jolt.cmake#L464-L469

JPH_PROFILE_ENABLED and JPH_FLOATING_POINT_EXCEPTIONS_ENABLED are public define that were missing

### CODE REVIEW

**Comment by SirLynix** [comment]
I'm not sure to understand why it fails on Fedora now.

It was working a few days ago: <https://github.com/xmake-io/xmake-repo/actions/runs/4753298381/jobs/8444708171>
But now fails: <https://github.com/xmake-io/xmake-repo/actions/runs/4810397967/jobs/8562963830?pr=2040>

Compiler update?

**Comment by waruqi** [comment]
> I'm not sure to understand why it fails on Fedora now.
> 
> It was working a few days ago: https://github.com/xmake-io/xmake-repo/actions/runs/4753298381/jobs/8444708171 But now fails: https://github.com/xmake-io/xmake-repo/actions/runs/4810397967/jobs/8562963830?pr=2040
> 
> Compiler update?

maybe, I rerun it, it does not work now.

**Comment by SirLynix** [comment]
This is caused by a missing include, see https://github.com/jrouwe/JoltPhysics/pull/517

I'm waiting for this to be merged to fix this package with a patch

**Comment by waruqi** [comment]
> This is caused by a missing include, see [jrouwe/JoltPhysics#517](https://github.com/jrouwe/JoltPhysics/pull/517)
> 
> I'm waiting for this PR to be merged to fix this package with a patch

you can use add_patches or io.replace to patch it first.

**Comment by SirLynix** [comment]
> you can use add_patches or io.replace to patch it first.

This is what I did to try to fix Fedora: https://github.com/SirLynix/xmake-repo/pull/9

I'm now waiting for my PR to be merged so I can provide a link to a Jolt commit as a patch, instead of my own Jolt fork (or adding a .patch file to xmake-repo)

**Pull request merged**
