### PR TITLE
Update xtensor

### PR DESCRIPTION
**Pull request by A2va**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by youngday** [comment]
xtensor-blas  install failed,log is blew:
```bash
(base) youngday@192:~$ xrepo install "xtensor-blas 0.20.0"
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> xtensor 0.24.7 [from:xtensor-blas]
please input: y (y/n/m)
y
  => install xtensor 0.24.7 .. failed

CMake Error at CMakeLists.txt:42 (find_package):
  Could not find a configuration file for package "xtl" that is compatible
  with requested version "0.7.5".
```

**Comment by A2va** [comment]
I have not been able to reproduce your problem on either Windows or Linux. What os are you using ?

**Comment by youngday** [comment]
in my  debian12,"xtensor  0.24.3","xtl 0.7.4","xtensor-blas 0.20.0" is installed before,when i update xmake and xrepo, "xtensor 0.24.7 " is installed,with "xtl 0.7.6",but in source code ,it depend on 0.7.5, xtl donot have this version in xrepo(0.7.4 and 0.7.6),when i reinstall  "xtensor-blas 0.20.0",it show info up comment, so it install "xtl 0.7.5 " manually, it resloved.

**Comment by A2va** [comment]
I see two ways to fix your problem:
1. Uninstall all xtensor related packages
2. Make a PR to add blas config to xtensor (like simd) and add a versions map between xtensor/xtensor-simd versions , xtensor/xtl and xtensor/xtensor-blas

**Pull request merged**
