### PR TITLE
add ogre-next

### PR DESCRIPTION
**Pull request by xq114**
macosx 上报错找不到符号sysctlbyname，我这没法调试

### CODE REVIEW

**Comment by SirLynix** [comment]
Since this package is not compatible with ogre1, shouldn't we call it ogre2 or ogre-next?

**Comment by waruqi** [comment]
> macosx 上报错找不到符号sysctlbyname，我这没法调试

    #include <sys/sysctl.h> 没加，master 版本似乎加上了，可以打个 patch，参考

https://github.com/OGRECave/ogre-next/blob/4b997cc4963f02ed12d694dfa87306bf8bfdc7e8/OgreMain/src/OgrePlatformInformation.cpp#L49-L52

**Comment by waruqi** [comment]
> Since this package is not compatible with ogre1, shouldn't we call it ogre2 or ogre-next?

@xq114 It might be more appropriate to change to ogre-next, keep it consistent with the name on the github repo

**Comment by xq114** [comment]
> Since this package is not compatible with ogre1, shouldn't we call it ogre2 or ogre-next?

Yes, ogre-next is a more appropriate name, since there is version 13.0.0 for ogre(1?). Mixing ogre and ogre-next can be confusing. I've renamed the package

**Pull request merged**
