### PR TITLE
Added Boost ICL and Interval to Boost xmake.lua

### PR DESCRIPTION
**Pull request by Theramar**
#2791

### CODE REVIEW

**Comment by Theramar** [comment]
I don't know what causes the failures

**Comment by evanzd** [comment]
@Theramar @waruqi This PR has caused our project to not build correctly. Could you offer any guidance on resolving this issue?
we are using `xmake` version 2.7.9 with boost as one of our dependencies:
```
add_requires("boost 1.81.0", {system = false, configs = {all = true, multi = true}})
```
xmake output:
```
checking for platform ... linux
checking for architecture ... x86_64
updating repositories .. ok
  => download https://github.com/fmtlib/fmt/releases/download/9.1.0/fmt-9.1.0.zip .. ok
  => install fmt 9.1.0 .. ok
  => download https://github.com/odygrd/quill/archive/refs/tags/v2.8.0.tar.gz .. ok
  => download https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.bz2 .. ok
  => install quill 2.8.0 .. ok
  => install boost 1.81.0 .. failed

error: wrong library name 'icl' in the --with-<library> option.
if you want to get more verbose errors, please see:
  -> /home/runner/.xmake/cache/packages/2311/b/boost/1.81.0/installdir.failed/logs/install.txt
error: install failed!
Error: Process completed with exit code 255.
```

**Comment by Theramar** [comment]
@evanzd I am not an expert... I would wait for @waruqi. In the meantime you could send us logs/install.txt and xmake output using -D (verbose diagnostics)

**Comment by evanzd** [comment]
We need to revert this commit because 'icl' and 'interval' are header-only libraries. You can verify my findings using the attached repository (use a clear environment without `boost` installed).
[repo.tgz](https://github.com/xmake-io/xmake-repo/files/13290304/repo.tgz)
[build_log.txt](https://github.com/xmake-io/xmake-repo/files/13290306/build_log.txt)

**Comment by waruqi** [comment]
> We need to revert this commit because 'icl' and 'interval' are header-only libraries. You can verify my findings using the attached repository (use a clear environment without `boost` installed). [repo.tgz](https://github.com/xmake-io/xmake-repo/files/13290304/repo.tgz) [build_log.txt](https://github.com/xmake-io/xmake-repo/files/13290306/build_log.txt)

right, we need not add them, I have reverted this patch.

**Pull request merged**
