### PR TITLE
dpp: update to v10.0.12

### PR DESCRIPTION
**Pull request by Bricklou**

### CODE REVIEW

**Comment by SirLynix** [comment]
Switch base from master to dev

**Comment by SirLynix** [comment]
Close and re-open the PR to trigger CI

**Comment by waruqi** [comment]
you need re-push it or re-open a new pr to dev branch to trigger ci tests.

**Comment by SirLynix** [comment]
Last time I closed it and reopened it after switching base, it worked (see #1291 )

**Comment by waruqi** [comment]
> Last time I closed it and reopened it after switching base, it worked (see #1291 )

oh, it works. 👍

**Pull request merged**
