### PR TITLE
reflect-cpp: fix deps

### PR DESCRIPTION
**Pull request by star-hengxing**

### CODE REVIEW

**Comment by requizm** [comment]
@star-hengxing I'm getting cmake error on v0.11.1. Could you check? (v.10.0 is fine)
```
  => install reflect-cpp v0.11.1 .. failed

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.38.CMake Error at CMakeLists.txt:53 (find_package):
  Could not find a package configuration file provided by "yyjson" with any
  of the following names:
    yyjsonConfig.cmake
    yyjson-config.cmake
  Add the installation prefix of "yyjson" to CMAKE_PREFIX_PATH or set
  "yyjson_DIR" to a directory containing one of the above files.  If "yyjson"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by star-hengxing** [comment]
> @star-hengxing I'm getting cmake error on v0.11.1. Could you check? (v.10.0 is fine)
> 
> ```
>   => install reflect-cpp v0.11.1 .. failed
> 
> -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
> -- The C compiler identification is MSVC 19.38.CMake Error at CMakeLists.txt:53 (find_package):
>   Could not find a package configuration file provided by "yyjson" with any
>   of the following names:
>     yyjsonConfig.cmake
>     yyjson-config.cmake
>   Add the installation prefix of "yyjson" to CMAKE_PREFIX_PATH or set
>   "yyjson_DIR" to a directory containing one of the above files.  If "yyjson"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> ```

Could you reinstall yyjson and try again, it should work.

```
$ xrepo remove --all -y yyjson
$ xrepo install reflect-cpp
````

**Comment by requizm** [comment]
@star-hengxing `yyjson 0.9.0` setup is ok. But `reflect-cpp v0.11.1` install gives an error. Here is the full log:
```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.40.CMake Error at CMakeLists.txt:53 (find_package):
  Could not find a package configuration file provided by "yyjson" with any
  of the following names:

    yyjsonConfig.cmake
    yyjson-config.cmake

  Add the installation prefix of "yyjson" to CMAKE_PREFIX_PATH or set
  "yyjson_DIR" to a directory containing one of the above files.  If "yyjson"
  provides a separate development package or SDK, be sure it has been
  installed.


Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
```

**Comment by star-hengxing** [comment]
> @star-hengxing `yyjson 0.9.0` setup is ok. But `reflect-cpp v0.11.1` install gives an error. Here is the full log:
> ```
> -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
> -- The C compiler identification is MSVC 19.40.CMake Error at CMakeLists.txt:53 (find_package):
>   Could not find a package configuration file provided by "yyjson" with any
>   of the following names:
> 
>     yyjsonConfig.cmake
>     yyjson-config.cmake
> 
>   Add the installation prefix of "yyjson" to CMAKE_PREFIX_PATH or set
>   "yyjson_DIR" to a directory containing one of the above files.  If "yyjson"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring incomplete, errors occurred!
> ```

I remove cmake install and directly copy header files. Update repo and try again.

**Comment by requizm** [comment]
@star-hengxing Thank you now it's working

**Pull request merged**
