### PR TITLE
add attr, acl and rsync

### PR DESCRIPTION
**Pull request by xq114**

### CODE REVIEW

**Comment by waruqi** [comment]
linux ci上加个 apt update 实数，感觉包源有点过期了。。

**Comment by waruqi** [comment]
很怪，这个 patch 里面 linux ci 就是有问题，我重新提了个patch就 ok，直接用这个吧 https://github.com/xmake-io/xmake-repo/pull/577

**Comment by SirLynix** [comment]
That's because I added apt update in https://github.com/xmake-io/xmake-repo/pull/574/files#diff-21364b2e6fae1f2875cee1ab3daefb0685403687eaf8bc32b5c6eacda351c9d3R26 (sorry for my chinese)

**Comment by waruqi** [comment]
> That's because I added apt update in https://github.com/xmake-io/xmake-repo/pull/574/files#diff-21364b2e6fae1f2875cee1ab3daefb0685403687eaf8bc32b5c6eacda351c9d3R26

oh, thanks!

**Pull request closed without merging**
