### PR TITLE
Add ShaderWriter

### PR DESCRIPTION
**Pull request by WubiCookie**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by WubiCookie** [comment]
I knew this wouldn't work on linux but I don't understand why.
On windows, I get
```
checking for xmake::shaderwriter ... shaderwriter master
{
  static = true,
  libfiles = {
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerGlsl.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerHlsl.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerSpirV.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\sdwShaderAST.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\sdwVulkanLayer.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\ShaderWriter.lib",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerGlsl.dll",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerHlsl.dll",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerSpirV.dll",
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwShaderWriter.dll"
  },
  links = {
    "CompilerGlsl",
    "CompilerHlsl",
    "CompilerSpirV",
    "sdwShaderAST",
    "sdwVulkanLayer",
    "ShaderWriter"
  },
  sysincludedirs = {
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\include"
  },
  linkdirs = {
    "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib"
  },
  version = "master"
}
```
but on linux, 
```
checking for xmake::shaderwriter ... shaderwriter master
{
  includedirs = {
    "/home/charles/.xmake/packages/s/shaderwriter/master/0edd84b48d4b4e7597f85ab3aa716322/include"
  },
  version = "master"
}
```
and still, the includes are missing since the on_test snippet fails with a 
```
fatal error: CompilerGLSL/compileGlsl.hpp: No such file or directory
             #include <CompilerGLSL/compileGlsl.hpp>
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by waruqi** [comment]
> I knew this wouldn't work on linux but I don't understand why.
> On windows, I get
> 
> ```
> checking for xmake::shaderwriter ... shaderwriter master
> {
>   static = true,
>   libfiles = {
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerGlsl.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerHlsl.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\CompilerSpirV.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\sdwShaderAST.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\sdwVulkanLayer.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib\ShaderWriter.lib",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerGlsl.dll",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerHlsl.dll",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwCompilerSpirV.dll",
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\bin\sdwShaderWriter.dll"
>   },
>   links = {
>     "CompilerGlsl",
>     "CompilerHlsl",
>     "CompilerSpirV",
>     "sdwShaderAST",
>     "sdwVulkanLayer",
>     "ShaderWriter"
>   },
>   sysincludedirs = {
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\include"
>   },
>   linkdirs = {
>     "C:\Users\Charles\AppData\Local\.xmake\packages\s\shaderwriter\master\c82b552ecf5d4943b33f0805174bfe1c\lib"
>   },
>   version = "master"
> }
> ```
> 
> but on linux,
> 
> ```
> checking for xmake::shaderwriter ... shaderwriter master
> {
>   includedirs = {
>     "/home/charles/.xmake/packages/s/shaderwriter/master/0edd84b48d4b4e7597f85ab3aa716322/include"
>   },
>   version = "master"
> }
> ```

The .a/.so library file is not found in the installdir directory, you need to confirm where cmake.install installed the library file, maybe you need to use os.cp to copy the library file to the lib directory


> 
> and still, the includes are missing since the on_test snippet fails with a
> 
> ```
> fatal error: CompilerGLSL/compileGlsl.hpp: No such file or directory
>              #include <CompilerGLSL/compileGlsl.hpp>
>                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

It should be `CompilerGlsl/compileGlsl.hpp`. Please note the case.

**Comment by waruqi** [comment]
> checking for xmake::shaderwriter ... shaderwriter master
{
  includedirs = {
    "/home/charles/.xmake/packages/s/shaderwriter/master/0edd84b48d4b4e7597f85ab3aa716322/include"
  },
  version = "master"
}

I found that on linux/macos the library name of this package installed in the `/installdr/lib` directory is like this

```
/Users/ruki/.xmake/packages/s/shaderwriter/master/d639b7d6e3244216b403b39df5101abf/lib/sdw
ShaderWriter.a
```

```
sdwShaderWriter.a
```

without `lib` prefix. ohmm...

This interferes with xmake's automatic lookup.

Maybe you need to use os.mv to rename them, or custom copy and install them.

**Comment by waruqi** [comment]
```lua
import("package.tools.cmake").install(package, configs, {buildir = "build"})
if not package:is_plat("windows") then
    os.trycp("build/xxx/sdwShaderWriter.a", package:installdir("lib/libsdwShaderWriter.a"))
end
```

**Comment by waruqi** [comment]
I have added it and fix links for linux. see https://github.com/xmake-io/xmake-repo/pull/216

**Comment by DragonJoker** [comment]
Hi,
I've updated ShaderWriter so the lib prefix on Linux is back.

**Comment by waruqi** [comment]
> Hi,
> I've updated ShaderWriter so the `lib` prefix on Linux is back.

Thanks, I have updated it. https://github.com/xmake-io/xmake-repo/pull/217

**Pull request closed without merging**
