### PR TITLE
Auto-update assimp to v5.3.1

### PR DESCRIPTION
**Pull request by SirLynix**
New version of assimp detected (package version: v5.2.5, last github version: v5.3.0)

### CODE REVIEW

**Comment by Latias94** [comment]
v5.3.1 just release lol

**Comment by SirLynix** [comment]
And it removes that utfcpp dependency 😑

**Comment by waruqi** [comment]
> (/home/runner/.xmake/cache/packages/2309/a/assimp/v5.3.1/source/contrib/unzip/ioapi.c:129)
>>>               ioapi.c.o:(fopen64_file_func) in archive 

we should check ndk version. https://github.com/xmake-io/xmake-repo/blob/3e6be8a7747d41092db4892e6648904a5b166c26/packages/l/llfio/xmake.lua#L67

BTW, it uses embed unzip source code. Maybe we should improve it to use external unzip deps.

**Comment by SirLynix** [comment]
You're right. Also now emscripten can't find zlib but it worked before. Could this be because or a change for cross platforms handling in xmake?

**Comment by waruqi** [comment]
> You're right. Also now emscripten can't find zlib but it worked before. Could this be because or a change for cross platforms handling in xmake?

I am not sure, you can switch to xmake 2.8.2 in wasm ci and test it again.

**Comment by waruqi** [comment]
> You're right. Also now emscripten can't find zlib but it worked before. Could this be because or a change for cross platforms handling in xmake?

it does not work for xmake 2.8.2 too.

**Comment by waruqi** [comment]
latest assimp version will break wasm.

**Comment by waruqi** [comment]
### 5.2.x

```
-- Looking for ZLIB...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Could not locate ZLIB
-- compiling zlib from sources
```

### 5.3.0

```
-- Looking for ZLIB...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Could not locate ZLIB
CMake Error at CMakeLists.txt:494 (message):
  Build configured with -DASSIMP_BUILD_ZLIB=OFF but unable to find zlib
```

zlib always is not found, but 5.2.x will compile embed zlib source, 5.3.x will abort.

**Comment by SirLynix** [comment]
@waruqi: Windows CI is blocked because it tries to download the master installer from the latest release which doesn't have it. Could you merge xmake dev into master to trigger CI?

**Comment by waruqi** [comment]
> @waruqi: Windows CI is blocked because it tries to download the master installer from the latest release which doesn't have it. Could you merge xmake dev into master to trigger CI?

sure, but maybe need to wait 1 hour at least. if https://github.com/xmake-io/xmake/actions/runs/6314361524 is finished, you can close and reopen it to trigger ci.

**Pull request merged**
