### PR TITLE
add stlab, easyloggingpp and matplotplusplus

### PR DESCRIPTION
**Pull request by xq114**

### CODE REVIEW

**Comment by waruqi** [comment]
> matplot\util\world_map_10m.cpp(16): error C2131: expression did not evaluate to a constant [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2108\m\matplotplusplus\v1.1.0\source\matplotplusplus-1.1.0\build_4037914C\source\matplot\matplot.vcxproj]
> matplot\util\world_map_10m.cpp(414749): error C2131: expression did not evaluate to a constant [C:\Users\runneradmin\AppData\Local\.xmake\cache\packages\2108\m\matplotplusplus\v1.1.0\source\matplotplusplus-1.1.0\build_4037914C\source\matplot\matplot.vcxproj]

> namespace matplot {
#ifdef MATPLOT_BUILD_HIGH_RESOLUTION_WORLD_MAP
    // (-?\d+\.\d+) +(-?\d+\.\d+) *\n
    // $1,\n
    // $2,\n
    // \n\n
    // \nstd::numeric_limits<double>::quiet_NaN(),\n
	std::pair<std::vector<double>, std::vector<double>> prepare_world_map_10m() {
        static constexpr double x[] = {
-71.31509355399993,
-71.304676886999914,
-71.30337480399993,
-71.317697719999899,
-71.33071855399993,
-71.335926886999914,
-71.343739386999914,
-71.355458136999914,
-71.359364386999914,
-71.356760219999899,
-71.335926886999914,
-71.33071855399993,
-71.337228969999899,
-71.337228969999899,
-71.33071855399993,
-71.31509355399993,
std::numeric_limits<double>::quiet_NaN(),
-67.566395636999914,
-67.566395636999914,

似乎 2016 上对 constexpr 不怎么支持。

可以判断下 vs 版本，禁用下这个试试：-DBUILD_HIGH_RESOLUTION_WORLD_MAP=OFF

```
# Include high-resolution world map in the binary
if (BUILD_HIGH_RESOLUTION_WORLD_MAP)
    target_compile_definitions(matplot PUBLIC MATPLOT_BUILD_HIGH_RESOLUTION_WORLD_MAP)
else ()
    message("Not including the high resolution maps for geoplots")
endif ()
```

**Comment by xq114** [comment]
> expression did not evaluate to a constant

https://stackoverflow.com/questions/63558400/vs2019-latest-update-constexpr-expression-did-not-evaluate-to-a-constant-for

这个看起来是VS的bug，可以把他改一下改成const，原来的代码应该还可用

**Comment by waruqi** [comment]
> https://stackoverflow.com/questions/63558400/vs2019-latest-update-constexpr-expression-did-not-evaluate-to-a-constant-for

那可以走 io.replace  patch下试试

**Comment by waruqi** [comment]
2016 跑了好久，我感觉这个 world_map_10m 太大了，io.replace 不一定能抗住，目前这个是一次性加载到内存做了 replace

**Comment by xq114** [comment]
看起来编译卡死了，就算能用应该也会出问题，还是低版本vs禁用算了

**Pull request merged**
