### PR TITLE
hidapi: support mingw

### PR DESCRIPTION
**Pull request by star-hengxing**
Fix https://github.com/xmake-io/xmake-repo/issues/4749

### CODE REVIEW

**Comment by star-hengxing** [comment]
@waruqi
hidapi 的 cmake 是用 pkg-config 找 libusb，但目前 package 导出 pkgconfig 是用 includedirs 而不是 sysincludedirs 导致这里报错了，不知道是不是 bug

```
cd /home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/build_e157a568/src/libusb && /usr/bin/clang-17 -Dhidapi_libusb_EXPORTS -I/home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/hidapi -I/home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb -isystem /home/runner/.xmake/packages/e/eudev/3.2.9/fa2cf6b4ed0749d79e1b44608f517996/include -isystem /home/runner/.xmake/packages/l/libusb/v1.0.27/e8ef0122c1084c1b965abac8974913c1/include -m64 -m64 -I/home/runner/.xmake/packages/e/eudev/3.2.9/fa2cf6b4ed0749d79e1b44608f517996/include -O3 -DNDEBUG -fPIC -MD -MT src/libusb/CMakeFiles/hidapi_libusb.dir/hid.c.o -MF CMakeFiles/hidapi_libusb.dir/hid.c.o.d -o CMakeFiles/hidapi_libusb.dir/hid.c.o -c /home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb/hid.c
/home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb/hid.c:44:10: fatal error: 'libusb.h' file not found
   44 | #include <libusb.h>
      |          ^~~~~~~~~~
1 error generated.
```

**Comment by waruqi** [comment]
> @waruqi hidapi 的 cmake 是用 pkg-config 找 libusb，但目前 package 导出 pkgconfig 是用 includedirs 而不是 sysincludedirs 导致这里报错了，不知道是不是 bug
> 
> ```
> cd /home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/build_e157a568/src/libusb && /usr/bin/clang-17 -Dhidapi_libusb_EXPORTS -I/home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/hidapi -I/home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb -isystem /home/runner/.xmake/packages/e/eudev/3.2.9/fa2cf6b4ed0749d79e1b44608f517996/include -isystem /home/runner/.xmake/packages/l/libusb/v1.0.27/e8ef0122c1084c1b965abac8974913c1/include -m64 -m64 -I/home/runner/.xmake/packages/e/eudev/3.2.9/fa2cf6b4ed0749d79e1b44608f517996/include -O3 -DNDEBUG -fPIC -MD -MT src/libusb/CMakeFiles/hidapi_libusb.dir/hid.c.o -MF CMakeFiles/hidapi_libusb.dir/hid.c.o.d -o CMakeFiles/hidapi_libusb.dir/hid.c.o -c /home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb/hid.c
> /home/runner/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb/hid.c:44:10: fatal error: 'libusb.h' file not found
>    44 | #include <libusb.h>
>       |          ^~~~~~~~~~
> 1 error generated.
> ```
> 
> 目前 fetch 的信息
> 
> ```
> {
>   links = "libusb-1.0",
>   libfiles = "C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\lib\libusb-1.0.lib",
>   static = true,
>   linkdirs = "C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\lib",
>   license = "LGPL-2.1",
>   sysincludedirs = {
>     "C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\include",
>     "C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\include\libusb-1.0"
>   },
>   version = "v1.0.27"
> }
> ```

跟 sysincludedirs 没啥关系，是这个包，llbusb.h 实际是在在 libusb-1.0 子目录下的。。

```
/home/ruki/.xmake/packages/l/libusb/v1.0.27/ef7ca18b1b414d72a35436321340f149/include
`-- libusb-1.0
    `-- libusb.h
```

但是 cmake 找到的 libusb 路径，只是根目录 `/home/ruki/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb`

所以只是路径不匹配，和 cmake 的库查找问题。

> cd /home/ruki/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/build_00397256/src/libusb && /usr/bin/cc  -I/home/ruki/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/hidapi -I/home/ruki/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb -isystem /home/ruki/.xmake/packages/e/eudev/3.2.9/022b93ec842a4cf88191a6c56aff29ab/include -isystem /home/ruki/.xmake/packages/l/libusb/v1.0.27/ef7ca18b1b414d72a35436321340f149/include -I/home/ruki/.xmake/packages/e/eudev/3.2.9/022b93ec842a4cf88191a6c56aff29ab/include -O3 -DNDEBUG -fPIC -MD -MT src/libusb/CMakeFiles/hidapi_libusb.dir/hid.c.o -MF CMakeFiles/hidapi_libusb.dir/hid.c.o.d -o CMakeFiles/hidapi_libusb.dir/hid.c.o -c /home/ruki/.xmake/cache/packages/2407/h/hidapi/0.14.0/source/libusb/hid.c

一种办法就是 patch 下 libusb 安装后的 lib/pkgconfig/libusb.pc ，追加 libusb-1.0 子目录，让cmake 能够找到正确路径就行了。

**Comment by star-hengxing** [comment]
> 跟 sysincludedirs 没啥关系，是这个包，llbusb.h 实际是在在 libusb-1.0 子目录下的。。

我知道，我的意思是，xmake 生成的 `.pc` 应该也要加上这个路径才对

```
"C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\include\libusb-1.0"
```

**Comment by waruqi** [comment]
> > 跟 sysincludedirs 没啥关系，是这个包，llbusb.h 实际是在在 libusb-1.0 子目录下的。。
> 
> 我知道，我的意思是，xmake 生成的 `.pc` 应该也要加上这个路径才对
> 
> ```
> "C:\Users\star\AppData\Local\.xmake\packages\l\libusb\v1.0.27\16614c59d01e4b9293fbd7242385e1b6\include\libusb-1.0"
> ```

改了下。

**Pull request merged**
