### PR TITLE
protobuf fPIC

### PR DESCRIPTION
**Pull request by maximegmd**
Fixes linker errors on linux when linking the library in a shared object.

### CODE REVIEW

**Comment by SirLynix** [comment]
this is already the default behavior of xmake when configuring cmake:
https://github.com/xmake-io/xmake/blob/6227615261ce6c2109c0c8324a83b582b25bd337/xmake/modules/package/tools/cmake.lua#L424-L426

maybe you disabled the pic config by mistake, or are having a particular configuration causing a bug?

**Comment by maximegmd** [comment]
It's just the standard setup on a github CI and we there is nothing that explicitly disables PIC anywhere.

https://github.com/tiltedphoques/CyberpunkMP/actions/runs/12000382045/job/33449425345?pr=14

**Comment by maximegmd** [comment]
The flag is indeed not passed

> /usr/local/bin/cmake -DSNAPPY_BUILD_TESTS=OFF -DSNAPPY_BUILD_BENCHMARKS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSNAPPY_REQUIRE_AVX=OFF -DSNAPPY_REQUIRE_AVX2=OFF -DSNAPPY_HAVE_BMI2=OFF -DCMAKE_INSTALL_PREFIX=/home/runner/.xmake/packages/s/snappy/1.1.10/badf6f1831764ca3b0e09f448f638f17 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_FIND_USE_CMAKE_SYSTEM_PATH=0 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=BOTH -DCMAKE_RANLIB=/usr/bin/ranlib -DCMAKE_STATIC_LINKER_FLAGS= -DCMAKE_C_FLAGS=-m64 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH -DCMAKE_FIND_USE_INSTALL_PREFIX=0 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 -DCMAKE_OSX_SYSROOT= -DCMAKE_EXE_LINKER_FLAGS=-m64 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_ASM_COMPILER=/usr/bin/gcc -DCMAKE_CXX_FLAGS=-m64 -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_ASM_FLAGS=-m64 -DCMAKE_AR=/usr/bin/ar -DCMAKE_SHARED_LINKER_FLAGS=-m64 "-DCMAKE_CXX_LINK_EXECUTABLE=/usr/bin/g++

**Comment by maximegmd** [comment]
https://github.com/xmake-io/xmake/issues/5881

**Pull request closed without merging**
