### PR TITLE
thrift: fix download

### PR DESCRIPTION
**Pull request by star-hengxing**

### CODE REVIEW

**Comment by star-hengxing** [comment]
windows arm ci🤔

```
"-DCMAKE_STATIC_LINKER_FLAGS_RELEASE=/machine:x64
```

**Comment by star-hengxing** [comment]
windows arm ci🤔

```
"-DCMAKE_STATIC_LINKER_FLAGS_RELEASE=/machine:x64
```

**Comment by waruqi** [comment]
> windows arm ci🤔
> 
> ```
> "-DCMAKE_STATIC_LINKER_FLAGS_RELEASE=/machine:x64
> ```

Maybe get incorrect default flags in this patch. https://github.com/xmake-io/xmake/pull/5025 @Arthapz

**Comment by waruqi** [comment]
wait https://github.com/xmake-io/xmake/pull/5115

**Pull request merged**
