### PR TITLE
boost: improve links

### PR DESCRIPTION
**Pull request by star-hengxing**
fix https://github.com/xmake-io/xmake-repo/issues/4263

Windows platform doesn't need to deal with link order

### CODE REVIEW

**Comment by SirLynix** [comment]
I don't think this is the right way to fix it, if the name are different then we should adapt the way we compute them

**Comment by SirLynix** [comment]
> If boost breaks the lib name in one day, this will make the package description more complex

We will need to do it anyway as we need them on other platforms

> And most xrepo packages don't need to deal with link order, What's so special about the boost library?

Nothing, all packages providing multiple libs depending on each other (A.so linked to B.so) need explicit link order.

**Comment by waruqi** [comment]
> If boost breaks the lib name in one day, this will make the package description more complex. And most xrepo packages don't need to deal with link order, What's so special about the boost library?

It doesn't simplify the package configuration of boost, as we still need to deal with the linking order on non-windows.

**Comment by star-hengxing** [comment]
I'm wondering if ld linker is the only one that needs to deal with link order. If so, then we don't need to waste too much time dealing with the some corner cases on links

https://github.com/xmake-io/xmake-repo/blob/129c8ccf8b9ba655042f927bfeda1030c4186b7c/packages/b/boost/xmake.lua#L97-L110

**Comment by SirLynix** [comment]
I think we should restore link order on Windows, as far as I know only MSVC linker doesn't care about link order, but not only MSVC linker can be used. You can compile using Clang/LLD for example.

**Comment by star-hengxing** [comment]
> I think we should restore link order on Windows, as far as I know only MSVC linker doesn't care about link order, but not only MSVC linker can be used. You can compile using Clang/LLD for example.

Can we use `package:has_tool`?
```lua
if not package:has_tool("ld", "linker") then
    -- link order
end
```

**Comment by SirLynix** [comment]
It wont help, we better just get the right name in all case and add links everytime imo

**Comment by star-hengxing** [comment]
Thanks for your reply. So we need to improve boost on_test.

**Pull request merged**
