### PR TITLE
add llama.cpp

### PR DESCRIPTION
**Pull request by waruqi**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by psych0v0yager** [comment]
Could we please get an updated version.

I tried to build the latest version of Llama.cpp by using the CMakeLists.txt from Llama.cpp on a Windows Machine and I ran into all sorts of errors.

**Comment by waruqi** [comment]
you can open a pr to update it

**Comment by psych0v0yager** [comment]
I am trying, but running in to errors.

Here is my attempt so far

```
set_project("llama")
set_languages("c99", "c++11")

-- Determine the build mode
if is_mode("release") then
    set_runtimes("Release")
else
    set_runtimes("Debug")
end

-- Add common build configurations
add_rules("mode.release", "mode.debug")

-- Check for CUDA support
option("cuda")
    set_default(true)
    set_showmenu(true)
    set_description("Enable CUDA support")
option_end()

-- Set output directory
set_targetdir("$(buildir)/bin")

-- Define the main library
target("ggml")
    set_kind("shared")
    add_files("ggml.c")
    add_files("ggml-alloc.c")
    add_files("ggml-backend.c")
    add_files("ggml-quants.c")
    add_headerfiles("ggml.h")
    add_headerfiles("ggml-alloc.h")
    add_headerfiles("ggml-backend.h")
    add_headerfiles("ggml-quants.h")

    if has_config("cuda") then
        -- Detect CUDA path
        local cuda_path = os.getenv("CUDA_PATH") or "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4"
        add_files("ggml-cuda/ggml-cuda.cu")
        add_headerfiles("ggml-cuda/ggml-cuda.h")
        add_defines("GGML_USE_CUDA")
        add_includedirs(path.join(cuda_path, "include"))
        add_linkdirs(path.join(cuda_path, "lib", "x64"))
        add_links("cuda", "cudart", "cublas", "cublasLt")
    end

    add_syslinks("pthread")
    add_includedirs(".")
    add_cxxflags("-Wall", "-Wextra", "-Wpedantic")
    if is_plat("linux") then
        add_defines("_GNU_SOURCE")
    elseif is_plat("macosx") then
        add_defines("_DARWIN_C_SOURCE")
    end

target("llama")
    set_kind("shared")
    add_files("llama.cpp", "unicode.cpp", "unicode-data.cpp")
    add_headerfiles("llama.h", "unicode.h")
    add_deps("ggml")
    add_includedirs(".")
    add_cxxflags("-Wall", "-Wextra", "-Wpedantic")

-- Define the options and targets
if has_config("cuda") then
    add_defines("LLAMA_CUDA")
end

-- Build and install scripts
on_install(function (target)
    os.cp("llama.h", path.join(target:installdir(), "include"))
    os.cp("unicode.h", path.join(target:installdir(), "include"))
    os.cp("$(buildir)/bin/*.dll", path.join(target:installdir(), "lib"))
end) 
```

```
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.39.33523
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(zig.exe version), No such file or directory
checking for zig ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
error: @programdir\core\main.lua:329: @programdir\core\sandbox\modules\import\core\base\task.lua:65: @programdir\core\project\project.lua:915: @programdir\modules\detect\sdks\find_cuda.lua:77: attempt to index a boolean value (local 'sdkdir')
stack traceback:
    [@programdir\modules\detect\sdks\find_cuda.lua:77]: in function '_find_cuda'
    [@programdir\modules\detect\sdks\find_cuda.lua:158]:
    [@programdir\rules\cuda\env\xmake.lua:25]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\project\target.lua:85]: in function '_load_rule'
    [@programdir\core\project\target.lua:110]: in function '_load_rules'
    [@programdir\core\project\target.lua:122]: in function '_load'
    [@programdir\core\project\project.lua:408]: in function '_load_targets'
    [@programdir\core\project\project.lua:913]: in function 'targets'
    [@programdir\actions\config\main.lua:116]: in function '_check_targets'
    [@programdir\actions\config\main.lua:395]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\sandbox\modules\import\core\base\task.lua:63]: in function 'run'
    [@programdir\actions\build\main.lua:191]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:275]:
    [@programdir\core\base\task.lua:491]: in function 'run'
    [@programdir\core\main.lua:327]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:973: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>
```

Specifically I keep getting a ```error: attempt to index a boolean value (local 'sdkdir')``` error when attempting to access the CUDA toolkit.

The original xmake file did not support Windows as Llama.cpp added windows support at a later time. Also I didn't find any mention of CUDA in the original, why was that so?

**Comment by waruqi** [comment]
you should use `xmake f --cuda=xxx` to set cuda sdk root path.

**Pull request merged**
