### PR TITLE
Update luau to 0.638

### PR DESCRIPTION
**Pull request by SirLynix**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by Chi-EEE** [comment]
mingw can be fixed by using this patch on isocline which is embedded in the project: https://github.com/xmake-io/xmake-repo/blob/dev/packages/i/isocline/xmake.lua#L13

**Comment by SirLynix** [comment]
Thank you.

I don't know why android broke from nowhere now, maybe a xmake change?

**Comment by star-hengxing** [comment]
Android r27 seems to break some packages.

**Comment by SirLynix** [comment]
the fix for android seems to be to require at least cmake 3.6: https://github.com/android/ndk/issues/2032

**Comment by c8ef** [comment]
Note that vcpkg suffers from the same issue: https://github.com/microsoft/vcpkg/pull/40339

I agree to roll back the NDK version update.

**Review by c8ef — APPROVED** [review]
Everything looks good now. I will send the necessary patch to the upstream.

**Pull request merged**
