### PR TITLE
Update Vulkan sdk packages to 1.3.246.1

### PR DESCRIPTION
**Pull request by SirLynix**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

### CODE REVIEW

**Comment by SirLynix** [comment]
it looks like meson is broken, I tried to update it to 1.1.0 but no luck

**Comment by waruqi** [comment]
> it looks like meson is broken on fedora, I tried to update it to 1.1.0 but no luck

you can try use previous version first. and open a new pr to update meson.

**Comment by SirLynix** [comment]
Meson 1.0 had the same issue, which is why I tried to update it

**Comment by waruqi** [comment]
maybe python3.11 issue? @xq114

**Comment by waruqi** [comment]
When looking for tools from xmake/packages, we should not look for it in the system environment. 

please wait for this patch. https://github.com/xmake-io/xmake/pull/3755

**Comment by waruqi** [comment]
> /tmp/pip-build-env-urh_dgtt/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`

it does not work for old python.

maybe pip/setuptools's issue?

**Comment by xq114** [comment]
The toolchain is gcc13 for fedora with gcc12 elsewise. There could be a compatibility issue.

**Comment by waruqi** [comment]
> The toolchain is gcc13 for fedora with gcc12 elsewise. There could be a compatibility issue.

I was able to fix this error by using the following patch.


```
package("meson")
        io.replace("setup.cfg", "license_file", "license_files")
```


But I continue to encounter other errors.

```console
File "/tmp/pip-build-env-hgsjrhp8/overlay/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/home/ruki/.xmake/packages/p/python/3.11.3/d8c248d43f4141a9b452cf40280c9f68/lib/python3.11/ctypes/__init__.py", line 8, in <module> import ctypes module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
```

**Comment by SirLynix** [comment]
I think it's because Fedora's Python doesn't have all we expect from a regular Python install (see https://github.com/mesonbuild/meson/issues/7885).

Maybe there's a conflict between xmake Python and Fedora Python?

**Comment by SirLynix** [comment]
Would it be possible to merge this, since meson broke on Fedora for other reasons?

**Comment by eli-schwartz** [comment]
> I think it's because Fedora's Python doesn't have all we expect from a regular Python install (see [mesonbuild/meson#7885](https://github.com/mesonbuild/meson/issues/7885)).

No, that bug report was from someone who compiled their own private python by downloading the Python source code and running `./configure && make && make install`, rather than using the Fedora python.



> But I continue to encounter other errors.
> 
> ```
> File "/tmp/pip-build-env-hgsjrhp8/overlay/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 43, in <module>
>           import ctypes
>         File "/home/ruki/.xmake/packages/p/python/3.11.3/d8c248d43f4141a9b452cf40280c9f68/lib/python3.11/ctypes/__init__.py", line 8, in <module> import ctypes module>
>           from _ctypes import Union, Structure, Array
>       ModuleNotFoundError: No module named '_ctypes'
> ```

This is coming from the xmake compiled version of python, so that's an xmake bug.

**Comment by waruqi** [comment]
```
		gcc -shared -fno-semantic-interposition -fprofile-generate build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/_ctypes.o build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/callbacks.o build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/callproc.o build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/cfield.o build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/stgdict.o -L/home/ruki/.xmake/packages/p/python/3.11.3/d8c248d43f4141a9b452cf40280c9f68/lib -L/usr/local/lib -ldl -o build/lib.linux-x86_64-3.11/_ctypes.cpython-311-x86_64-linux-gnu.so
*** WARNING: renaming "_ctypes" since importing it failed: /home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/build/lib.linux-x86_64-3.11/_ctypes.cpython-311-x86_64-linux-gnu.so: undefined symbol: ffi_type_void

The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _tkinter           
_uuid                 nis                   readline           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py have not
been built, they are *disabled* by configure:
_sqlite3                                                       


Following modules built successfully but were removed because they could not be imported:
_ctypes                     
```

> *** WARNING: renaming "_ctypes" since importing it failed: /home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/build/lib.linux-x86_64-3.11/_ctypes.cpython-311-x86_64-linux-gnu.so: undefined symbol: ffi_type_void

ffi link is missing when building python ctypes module.

**Comment by waruqi** [comment]
But I don't know why python didn't find the libffi package provided by xmake, just the missing links, includedirs can be found.

```
gcc -fPIC -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-generate -I./Include/internal -I./Include -I. -I/home/ruki/.xmake/packages/z/zlib/v1.2.13/6c2566e3272548ea9aa218b4a6537908/include -I/home/ruki/.xmake/packages/l/libffi/3.4.4/27a00d8523ca46058a204ca1fa256bc1/include -I/usr/local/include -I/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Include -I/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source -c /home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/stgdict.c -o build/temp.linux-x86_64-3.11/home/ruki/.xmake/cache/packages/2305/p/python/3.11.3/source/Modules/_ctypes/stgdict.o
```

**Comment by waruqi** [comment]
```
bash-5.2$ tree ~/.xmake/packages/l/libffi/3.4.4/27a00d8523ca46058a204ca1fa256bc1
/home/ruki/.xmake/packages/l/libffi/3.4.4/27a00d8523ca46058a204ca1fa256bc1
|-- include
|   |-- ffi.h
|   `-- ffitarget.h
|-- lib
|   `-- pkgconfig
|       `-- libffi.pc
|-- lib64
|   |-- libffi.a
|   `-- libffi.la
|-- manifest.txt
|-- references.txt
`-- share

```

It seems that when building libffi, the `--libdir=` argument doesn't take full effect, the .a library is always installed in lib64, but the pc files are installed in the lib directory

**Comment by waruqi** [comment]
this patch should fix it. 


https://github.com/xmake-io/xmake-repo/pull/2129

**Pull request merged**
