### PR TITLE
Add libvorbis

### PR DESCRIPTION
**Pull request by SirLynix**
From #203

### CODE REVIEW

**Comment by SirLynix** [comment]
Seems related to https://github.com/xiph/vorbis/issues/67, maybe it needs some patching

**Comment by waruqi** [comment]
> CMake Error at C:/Users/runneradmin/AppData/Local/.xmake/packages/c/cmake/3.18.4/7001040a8533492597b595810d0adc4e/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
-- Configuring incomplete, errors occurred!
  Could NOT find Ogg (missing: OGG_LIBRARY OGG_INCLUDE_DIR)
See also "C:/Users/runneradmin/AppData/Local/.xmake/cache/packages/2012/l/libvorbis/1.3.7/source/libvorbis-1.3.7/build_630A129B/CMakeFiles/CMakeOutput.log".

I saw https://github.com/xiph/vorbis/blob/master/cmake/FindOgg.cmake

```
find_path(OGG_INCLUDE_DIR ogg/ogg.h
    HINTS
        ${PC_OGG_INCLUDEDIR}
        ${PC_OGG_INCLUDE_DIRS}
        ${OGG_ROOT}
    PATH_SUFFIXES
        include
)
# MSVC built ogg may be named ogg_static.
# The provided project files name the library with the lib prefix.
find_library(OGG_LIBRARY
    NAMES
        ogg
        ogg_static
        libogg
        libogg_static
    HINTS
        ${PC_OGG_LIBDIR}
        ${PC_OGG_LIBRARY_DIRS}
        ${OGG_ROOT}
    PATH_SUFFIXES
        lib
)
```

Can you try pass PC_OGG_LIBDIR, PC_OGG_INCLUDEDIR instead of OGG_INCLUDE_DIR/OGG_LIBRARY

I think `cmake/find_library(OGG_INCLUDE_DIR)` will rewrite  OGG_INCLUDE_DIR.

**Comment by waruqi** [comment]
Or try only pass `"-DOGG_ROOT=" .. package:dep("libogg"):installdir()`?

**Comment by SirLynix** [comment]
Neither seems to be working 😞

**Comment by waruqi** [comment]
I have added it. see https://github.com/xmake-io/xmake-repo/pull/211

**Pull request closed without merging**
