### PR TITLE
Add extsources to atk

### PR DESCRIPTION
**Pull request by ImperatorS79**
I removed cairo to see if it works.

### CODE REVIEW

**Comment by waruqi** [comment]
Can you help me to add pkgconfig::xx extsources? it will be more accurate than apt::

**Comment by waruqi** [comment]
pcre url broken, maybe you need wait for https://github.com/xmake-io/xmake-repo/pull/677

**Comment by waruqi** [comment]
pcre has been fixed

**Comment by waruqi** [comment]
Since you modify too many packages at once, this will trigger a large number of builds. On msys ci, it was too slow, so it was forcibly cancelled.

In addition, the collada-dom package will be broken on windows 2016.

I suggest to split it into multiple smaller prs to facilitate the passage and merging of ci. We can also temporarily ignore the problematic collada-dom so that we can fix it in a targeted manner later.

**Comment by ImperatorS79** [comment]
The failing step fails because https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz returns error 404 but it works for me.

**Comment by waruqi** [comment]
I rerun it.

**Comment by waruqi** [comment]
thanks

**Pull request merged**
