### PR TITLE
Update ExprTk to tag 0.0.2

### PR DESCRIPTION
**Pull request by ArashPartow**

### CODE REVIEW

**Comment by waruqi** [comment]
please push to dev branch to trigger ci

**Comment by ArashPartow** [comment]
@waruqi would you happen to know how this issues can be resolved? 

> checkinfo: ...amdir\core\sandbox\modules\import\core\tool\compiler.lua:84: @programdir\modules\core\tools\gcc.lua:713: D:\a\_temp\msys64\tmp\ccLlZBV5.s: Fatal error: D:\a\_temp\msys64\tmp\.xmake\230216\_8DFAF9AD7FCF4C1088E16B9DCA3E9240.o: file too big
>   > in D:\a\_temp\msys64\tmp\.xmake\230216\_4808B1B285934C339AB4B6D9EFB05691.cpp
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:898]:
>     [@programdir\modules\core\tools\gcc.lua:713]: in function 'catch'
>     [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
>     [@programdir\modules\core\tools\gcc.lua:6[54](https://github.com/xmake-io/xmake-repo/actions/runs/4199071729/jobs/7283497620#step:5:55)]:
>     [C]: in function 'xpcall'


this is from the mingw msys2 build in the above pipeline.

**Comment by waruqi** [comment]
I don't know, I have set `-Wa,-mbig-obj` flags. Maybe you need disable mingw platform.

**Comment by ArashPartow** [comment]
@waruqi  I've been able to build it using mingw cross compiler on linux - but this may not be the same process as performing the  build on a windows box. This is a weird one.  ld has always been unreliable on windows.

**Comment by waruqi** [comment]
Yes, but at the moment I have no better solution than to disable it for now.

**Pull request merged**
