### PR TITLE
[commonlibsse-ng] Add `v3.7.0`

### PR DESCRIPTION
**Pull request by Qudix**
Add `v3.7.0` to `commonlibsse-ng`

### CODE REVIEW

**Comment by Qudix** [comment]
Ugh, fmt made a breaking change

**Comment by Qudix** [comment]
I'm unsure if forcing versions is the best solution

**Comment by waruqi** [comment]
> I'm unsure if forcing versions is the best solution

It is not recommended to write a fixed version.

**Comment by Qudix** [comment]
Not sure how else to fix it then, spdlog won't compile with fmt version 10.0.0 due to this: https://github.com/gabime/spdlog/issues/2693

**Comment by waruqi** [comment]
You can wait for spdlog to be fixed and use the next version. Or you can use add_patches to make a temporary fix to the current version to make it compatible.

**Pull request merged**
